#pragma once

#include <random>

#include "TreeParameters.h"
#include "TreeStructure.h"
#include "api.h"

namespace TreeGen {

// Developmental tree model following Stava et al. 2014, Section 4 ("Used
// Procedural Model"), with the light model in the spirit of Pirk et al. 2012
// (PSK*12) and per-node gravity bending from its Appendix A.
class TREEGEN_API TreeGrowth {
   public:
    TreeGrowth(const TreeParameters& params);

    // Initialize a new tree with a single trunk
    TreeStructure initialize_tree();

    // Perform one growth cycle
    void grow_one_cycle(TreeStructure& tree);

    // Grow tree for multiple cycles
    void grow_tree(TreeStructure& tree, int cycles);

    // Place leaves along terminal branches (Section 4.2: foliage is
    // generated procedurally at the END of the growth cycle)
    void generate_foliage(TreeStructure& tree);

   private:
    TreeParameters params_;
    std::mt19937 rng_;
    std::normal_distribution<float> normal_dist_;
    std::uniform_real_distribution<float> uniform_dist_;

    // Initialize random number generator
    void init_random();

    // Get random value from normal distribution
    float random_normal(float mean, float stddev);

    // Get random value from uniform distribution
    float random_uniform(float min = 0.0f, float max = 1.0f);

    // ===== Bud Management =====

    // Bud extinction (phi_ABD / phi_LBD per cycle) + aging
    void update_bud_states(TreeStructure& tree);

    // Calculate illumination for all living buds (simplified height model)
    void calculate_illumination(TreeStructure& tree);

    // Auxin received by each lateral bud from buds that flushed during the
    // previous cycle, summed with branch-wise distance (Eq. 3)
    void calculate_auxin_levels(TreeStructure& tree);

    // Auxin contribution accumulated along the path from bud to the root
    float compute_auxin_for_bud(const TreeBud& bud, const TreeStructure& tree);

    // Determine which buds will flush (grow) this cycle — Eqs. 2 and 3
    void determine_bud_flushing(TreeStructure& tree);

    // ===== Shoot Growth =====

    // Grow a new shoot from a bud
    void grow_shoot_from_bud(TreeStructure& tree, std::shared_ptr<TreeBud> bud);

    // Number of internodes generated by a shoot (Eq. 1; apical control with
    // age factor, exponent is the parent-branch level)
    float calculate_growth_rate(int branch_level, int tree_age);

    // Internode length at a given tree age (phi_IBL * phi_ILAF^t)
    float calculate_internode_length(int tree_age);

    // Create the internode chain of a shoot; tropisms are applied PER
    // INTERNODE (Palubicki et al. 2009 approach)
    void create_internodes(
        TreeStructure& tree,
        std::shared_ptr<TreeBranch> parent,
        const glm::vec3& start_pos,
        const glm::vec3& initial_dir,
        int num_internodes,
        int branch_level,
        float bud_illumination,
        const glm::vec3& bud_light_dir);

    // ===== Direction and Tropism =====

    // Per-internode tropism step: phototropism towards the bud's LOCAL light
    // direction, gravitropism away from gravity
    glm::vec3 apply_tropism(
        const glm::vec3& direction,
        float illumination,
        const glm::vec3& local_light_dir);

    // Apical bud spherical angle: theta ~ N(0, phi_AAV), phi ~ U(0, 2pi)
    glm::vec3 apply_apical_spherical_angle(const glm::vec3& direction);

    // ===== Lateral Bud Creation =====

    // Create the lateral buds of one node (internode boundary)
    void create_lateral_buds(
        std::shared_ptr<TreeBranch> branch,
        int node_index);

    // Branching direction of one lateral bud: roll from phyllotaxis
    // (per-node golden roll * per-bud even spacing), tilt by branching angle
    glm::vec3 calculate_lateral_direction(
        const glm::vec3& parent_dir,
        int bud_index,
        int total_buds,
        int node_index);

    // ===== Structural Updates =====

    // Pipe model: r_parent^2 = sum of r_child^2, tips at phi_initial
    void update_branch_radii(TreeStructure& tree);

    // Gravity bending (Appendix A): f_b, beta_max, accumulated beta
    void apply_structural_bending(TreeStructure& tree);

    // Shedding: low lateral branches (below phi_LBPF) and shadowed branches
    // (illumination < phi_PF) are REMOVED from the tree
    void prune_branches(TreeStructure& tree);

    // ===== Leaf Generation (Section 4.2) =====

    // Place leaves along one branch (terminal branches in the default setup)
    void create_leaves_on_branch(std::shared_ptr<TreeBranch> branch);

    // ===== Illumination (Pirk et al. 2012 style) =====

    // Build proxy foliage clusters used by the light model during growth
    void create_leaf_clusters(TreeStructure& tree);

    // Illumination for every living bud and branch via cluster shadows
    void calculate_illumination_with_clusters(TreeStructure& tree);

    // Hemisphere-sampled visibility with cluster occlusion; optionally
    // returns the visibility-weighted average light direction
    float calculate_point_illumination(
        const glm::vec3& point,
        const TreeStructure& tree,
        const glm::vec3& light_dir,
        glm::vec3* out_light_direction = nullptr);

    // ===== Utility Functions =====

    // Rotate vector around axis
    glm::vec3
    rotate_vector(const glm::vec3& vec, const glm::vec3& axis, float angle);

    // Get perpendicular vector
    glm::vec3 get_perpendicular(const glm::vec3& vec);
};

}  // namespace TreeGen
