"""Headless end-to-end test for the character walking simulator.

Pipeline under test (all inside Stage.tick, no window required):

    InputState axis override --\
                                +--> CharacterControllerSystem
    USD scene (character:controller = true) --/

  * discovery of the /Character prim via the `character:controller` marker
  * skeleton build from the USD joint hierarchy (Hips/.../L_Foot)
  * kinematic movement (position integrate + heading smoothing)
  * procedural gait authored as translate/rotate overs in the session
    (modifier) layer — read back from the composed stage
  * stop behavior once the axis override is released

Scene is generated by scripts/gen_character_walk_scene.py.
Environment is set up by source/tests/conftest.py.
"""

import subprocess
import sys
from pathlib import Path

import pytest

from conftest import TEST_OUTPUT_DIR

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
BINARY_DIR = PROJECT_ROOT / "Binaries" / "Release"
GEN_SCRIPT = PROJECT_ROOT / "scripts" / "gen_character_walk_scene.py"

DT = 1.0 / 60.0


@pytest.fixture
def scene_path(tmp_path):
    """Fresh scene per test. Stage(path) reloads the _modifiers sidecar and
    the controller resumes the last authored position — a persistent scene
    would make test 2 continue test 1's walk."""
    out = tmp_path / "character_walk.usda"
    proc = subprocess.run(
        [sys.executable, str(GEN_SCRIPT), "-o", str(out)],
        capture_output=True, text=True)
    assert proc.returncode == 0, proc.stderr
    return out


def _modifier_layer(stage):
    """Session (modifier) layer holding the controller's authored overs.

    Read spec-level (Sdf) rather than through a composed pxr.Usd.Stage —
    `get_pxr_stage()` needs Boost.Python wrappers that are not always
    registered in this process, while Layer.Find on the modifier layer
    identifier is the supported headless path.
    """
    from pxr import Sdf
    return Sdf.Layer.Find(stage.get_modifier_layer_identifier())


def _attr_default(layer, prim_path, attr_name):
    """Spec-level attribute default, or None when not authored (yet).

    Property paths must be fully qualified ("/Character.xformOp:transform"):
    the colon in namespaced attributes does not parse as a standalone
    SdfPath, so SdfPrimSpec::GetAttributeAtPath("xformOp:transform") is
    ill-formed.
    """
    try:
        prop = layer.GetPropertyAtPath(f"{prim_path}.{attr_name}")
        return prop.default
    except Exception:
        return None


def _root_translate(layer):
    matrix = _attr_default(layer, "/Character", "xformOp:transform")
    if matrix is None:
        return None
    t = matrix.ExtractTranslation()
    return (t[0], t[1], t[2])


def _thigh_rotation(layer, side="L"):
    matrix = _attr_default(
        layer, f"/Character/Hips/{side}_Thigh", "xformOp:transform")
    if matrix is None:
        return None
    from pxr import Gf
    euler = matrix.ExtractRotation().Decompose(
        Gf.Vec3d(1, 0, 0), Gf.Vec3d(0, 1, 0), Gf.Vec3d(0, 0, 1))
    return (euler[0], euler[1], euler[2])


def test_character_walks_forward_and_animates(scene_path):
    import stage_py

    stage = stage_py.Stage(str(scene_path))
    stage.set_move_input(0.0, 1.0)  # forward (+Y, identity view frame)

    max_thigh_swing = 0.0
    for _ in range(90):
        stage.tick(DT)
        rot = _thigh_rotation(_modifier_layer(stage))
        if rot is not None:
            max_thigh_swing = max(max_thigh_swing, abs(rot[0]))

    translate = _root_translate(_modifier_layer(stage))
    assert translate is not None, "controller never authored the root pose"
    x, y, z = translate
    # 90 ticks = 1.5 s with speed ramping to 3 m/s -> ~3.3 m forward.
    assert y > 2.5, f"character barely moved: translate={(x, y, z)}"
    assert abs(x) < 0.1, f"stray lateral drift: translate={(x, y, z)}"
    assert 0.0 <= z < 0.2, f"character left the ground: z={z}"
    # Procedural gait must actually swing the legs (>5 degrees at peak).
    assert max_thigh_swing > 5.0, f"legs never swung: {max_thigh_swing}"

    stage.clear_move_input()


def test_character_turns_and_stops(scene_path):
    import stage_py

    stage = stage_py.Stage(str(scene_path))

    # Walk sideways (+X in view space): heading converges to atan2(-1, 0)
    # = -pi/2 -> rotateZ = -90 degrees; position advances along +X.
    stage.set_move_input(1.0, 0.0)
    for _ in range(60):
        stage.tick(DT)
    layer = _modifier_layer(stage)
    translate = _root_translate(layer)
    assert translate is not None, "controller never authored the root pose"
    x, y, _ = translate
    assert x > 1.0, f"expected +X travel, translate={(x, y)}"
    from pxr import Gf
    rot = _attr_default(layer, "/Character", "xformOp:transform")
    heading_z = (
        rot.ExtractRotation().Decompose(
            Gf.Vec3d(1, 0, 0), Gf.Vec3d(0, 1, 0), Gf.Vec3d(0, 0, 1))[2]
        if rot is not None else None)
    assert heading_z is not None and abs(heading_z - (-90.0)) < 5.0, (
        f"heading did not converge: {heading_z}")

    # Release input: velocity decays, then the character stands still.
    stage.clear_move_input()
    for _ in range(30):
        stage.tick(DT)
    pos_a = _root_translate(_modifier_layer(stage))
    for _ in range(60):
        stage.tick(DT)
    pos_b = _root_translate(_modifier_layer(stage))
    drift = abs(pos_b[0] - pos_a[0]) + abs(pos_b[1] - pos_a[1])
    assert drift < 0.2, f"character kept drifting after release: {drift}"
