"""
White furnace test — energy conservation for a single BSDF scatter.

Scene: a fully-white (albedo=1, roughness=1 = pure diffuse) sphere in a
uniform environment (DomeLight Le=1). For a correct path tracer the sphere's
outgoing radiance integrates to exactly Le, so the sphere must be
indistinguishable from the background:

    sphere_mean / environment_mean == 1.0   (within tolerance)

A ratio above 1.0 means energy is being *gained* (throughput over-estimated,
e.g. a missing cos(theta) division or an under-estimated sampling pdf); a
ratio below 1.0 means energy is being *lost* (throughput under-estimated).
The sphere region must also be spatially uniform (std ~ 0) — a shaded ball
would indicate the BSDF response is not integrating to the albedo.

This is the regression guard for the MIS/pdf work: both the conditional-vs-
marginal pdf bug (fireflies) and the NdotL throughput question show up here.

Scene: data/scenes/white_furnace.usda (generated by pxr — uses the USD
Sphere prim, NOT a hand-written mesh: hand-written UV spheres with pole
degenerate triangles rendered as a flat silhouette and broke this test).
"""

from pathlib import Path
import numpy as np
import pytest

from conftest import TEST_OUTPUT_DIR

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
BINARY_DIR = PROJECT_ROOT / "Binaries" / "Release"
DATA_DIR = Path(__file__).resolve().parent / "data"
OUTPUT_DIR = Path(TEST_OUTPUT_DIR) / "white_furnace"

SCENE = DATA_DIR / "scenes" / "white_furnace.usda"

# How close the sphere/environment ratio must be to 1.0. Monte-Carlo noise at
# 512 SPP is ~1e-4, so 0.5% is a generous but meaningful bound: a 4% energy
# loss (the pre-fix behavior) fails loudly.
RATIO_TOL = 0.005
# The sphere interior must be essentially flat (no shading gradient).
STD_TOL = 0.005


def _render(scene_path, width=128, height=128, samples=512):
    """Render the furnace scene via the standard path-tracing pipeline."""
    import hd_RUZINO_py as renderer
    from test_render_materials import _build_render_graph

    hydra = renderer.HydraRenderer(str(scene_path), width, height)
    _build_render_graph(hydra, samples)
    for _ in range(samples):
        hydra.render()
    texture_data = hydra.get_output_texture()
    img = np.array(texture_data, dtype=np.float32).reshape(height, width, 4)
    img = np.flipud(img)  # GPU origin top-left; scene is Y-up
    return img


def _save_image(img, name):
    """Save rendered image for inspection under test_output/."""
    import os
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    np.save(OUTPUT_DIR / f"{name}.npy", img)
    rgb = np.clip(img[:, :, :3], 0, 1)
    rgb = (rgb * 255).astype(np.uint8)
    try:
        from PIL import Image
        Image.fromarray(rgb).save(OUTPUT_DIR / f"{name}.png")
    except ImportError:
        pass
    print(f"Saved: {name} shape={img.shape} mean={img[:,:,:3].mean():.4f}")


def test_white_furnace_energy_conservation():
    """Sphere (albedo=1) must vanish into the uniform environment (ratio=1)."""
    if not SCENE.exists():
        pytest.skip(f"{SCENE} not found")

    img = _render(SCENE, width=128, height=128, samples=512)
    _save_image(img, "white_furnace_512")

    rgb = img[..., :3]
    flat = rgb.reshape(-1, 3).max(axis=1).reshape(128, 128)

    # Camera at z=8, sphere r=1: the sphere spans ~y/x [18,109] of the 128px
    # frame. Interior region excludes the rim (anti-aliasing) and corners
    # sample the environment.
    sphere = flat[40:88, 40:88]
    env = flat[0:8, 0:8]

    sphere_mean = float(sphere.mean())
    env_mean = float(env.mean())
    ratio = sphere_mean / env_mean

    print(f"sphere mean = {sphere_mean:.4f}")
    print(f"environment mean = {env_mean:.4f}")
    print(f"ratio = {ratio:.6f}  (tolerance ±{RATIO_TOL})")

    assert env_mean > 0.1, f"environment unexpectedly dark: {env_mean:.4f}"
    assert abs(ratio - 1.0) <= RATIO_TOL, (
        f"energy not conserved: sphere/env = {ratio:.4f} "
        f"(expect 1.0 ± {RATIO_TOL}). Throughput over/under-estimated."
    )

    # The sphere must be spatially uniform (pure diffuse + uniform env = flat).
    sphere_std = float(sphere.std())
    print(f"sphere interior std = {sphere_std:.6f}  (tolerance {STD_TOL})")
    assert sphere_std <= STD_TOL, (
        f"sphere not uniform (std={sphere_std:.4f}): "
        f"BSDF response is not integrating to albedo."
    )
