if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/../source/Core/rznode/cmake/AddLibrary.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/../source/Core/rznode/cmake/AddLibrary.cmake")
elseif(EXISTS "${CMAKE_CURRENT_LIST_DIR}/rznode/AddLibrary.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/rznode/AddLibrary.cmake")
else()
    message(FATAL_ERROR "Cannot find rznode/AddLibrary.cmake. Please ensure rznode submodule is initialized.")
endif()
